"""empty message

Revision ID: b3307a7c3e26
Revises: 5fff92a336a0
Create Date: 2024-10-31 09:06:41.351315

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "b3307a7c3e26"
down_revision: Union[str, None] = "5fff92a336a0"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user",
        sa.Column(
            "lattitude", sa.Float(), nullable=False, server_default=str(0.0)
        ),
    )
    op.add_column(
        "user",
        sa.Column(
            "longitude", sa.Float(), nullable=False, server_default=str(0.0)
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "longitude")
    op.drop_column("user", "lattitude")
    # ### end Alembic commands ###
